// <auto-generated />
using System;
using FleetOps.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetOps.Api.Migrations
{
    [DbContext(typeof(FleetOpsDbContext))]
    [Migration("20260802073000_AddVehicleAssignmentAndFuelRecord")]
    partial class AddVehicleAssignmentAndFuelRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10").HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Driver", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateOnly>("DriverLicenseExpiryDate").HasColumnType("date");
                b.Property<string>("DriverLicenseNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateOnly>("HireDate").HasColumnType("date"); b.Property<int>("Status").HasColumnType("int"); b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id"); b.HasIndex("DriverLicenseNumber").IsUnique(); b.HasIndex("UserId").IsUnique(); b.ToTable("Drivers", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Role", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier"); b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id"); b.HasIndex("Name").IsUnique(); b.ToTable("Roles", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier"); b.Property<DateOnly>("DateOfBirth").HasColumnType("date");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)"); b.Property<string>("LastName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier"); b.Property<int>("Status").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(1);
                b.HasKey("Id"); b.HasIndex("Email").IsUnique(); b.HasIndex("RoleId"); b.ToTable("Users", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Vehicle", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier"); b.Property<string>("Brand").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("FuelType").HasColumnType("int"); b.Property<int>("Mileage").HasColumnType("int"); b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PlateNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)"); b.Property<int>("Status").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(1);
                b.Property<string>("Vin").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)"); b.Property<int>("Year").HasColumnType("int");
                b.HasKey("Id"); b.HasIndex("PlateNumber").IsUnique(); b.HasIndex("Vin").IsUnique(); b.ToTable("Vehicles", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.FuelRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier"); b.Property<int>("FuelType").HasColumnType("int"); b.Property<int>("Mileage").HasColumnType("int");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnType("decimal(10,2)"); b.Property<DateTime>("RefueledAt").HasColumnType("datetime2");
                b.Property<Guid>("VehicleId").HasColumnType("uniqueidentifier"); b.Property<decimal>("Volume").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                b.HasKey("Id"); b.HasIndex("VehicleId", "RefueledAt"); b.ToTable("FuelRecords", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.VehicleAssignment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier"); b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                b.Property<Guid>("DriverId").HasColumnType("uniqueidentifier"); b.Property<DateTime?>("UnassignedAt").HasColumnType("datetime2"); b.Property<Guid>("VehicleId").HasColumnType("uniqueidentifier");
                b.HasKey("Id"); b.HasIndex("DriverId"); b.HasIndex("VehicleId", "UnassignedAt").IsUnique().HasFilter("[UnassignedAt] IS NULL"); b.ToTable("VehicleAssignments", (string)null);
            });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Driver", b => { b.HasOne("FleetOps.Api.Domain.Entities.User", "User").WithOne("Driver").HasForeignKey("FleetOps.Api.Domain.Entities.Driver", "UserId").OnDelete(DeleteBehavior.NoAction).IsRequired(); b.Navigation("User"); b.Navigation("VehicleAssignments"); });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.User", b => { b.HasOne("FleetOps.Api.Domain.Entities.Role", "Role").WithMany("Users").HasForeignKey("RoleId").OnDelete(DeleteBehavior.NoAction).IsRequired(); b.Navigation("Role"); b.Navigation("Driver"); });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.FuelRecord", b => { b.HasOne("FleetOps.Api.Domain.Entities.Vehicle", "Vehicle").WithMany("FuelRecords").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.NoAction).IsRequired(); b.Navigation("Vehicle"); });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.VehicleAssignment", b => { b.HasOne("FleetOps.Api.Domain.Entities.Driver", "Driver").WithMany("VehicleAssignments").HasForeignKey("DriverId").OnDelete(DeleteBehavior.NoAction).IsRequired(); b.HasOne("FleetOps.Api.Domain.Entities.Vehicle", "Vehicle").WithMany("VehicleAssignments").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.NoAction).IsRequired(); b.Navigation("Driver"); b.Navigation("Vehicle"); });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Role", b => { b.Navigation("Users"); });
            modelBuilder.Entity("FleetOps.Api.Domain.Entities.Vehicle", b => { b.Navigation("FuelRecords"); b.Navigation("VehicleAssignments"); });
#pragma warning restore 612, 618
        }
    }
}
